apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    test: nginx
  name: nginx
  namespace: numaplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      test: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
