apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    test: nginx
  name: nginx
  namespace: numaplane-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
