apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: nginx
  type: {{ .Values.service.type }}